### ISSUE TITLE
BigNumber.from overflow error

### ISSUE THREAD

**Issue by mazgalesc** [flashbots/simple-blind-arbitrage#15]
Here is the complete error with the context.

Transaction trading on Uniswap v2 pool detected! Pool address: 0x28cee28a7c4b4022ac92685c07d2f33ab1a0e122
Pool contract created, getting tokens
Token0: 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984
Token1: 0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6
Factory: 0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f
Pool is WETH pair
Pool is Uniswap v2
Checking alternative factor for pair
Alternate pair exists! Pair address: 0x6D2fAf643Fe564e0204f35e38d1a1b08D9620d14
Sending bundles to MEV-Share Node for tx: 0xb496066791af51c3bbbfa82c98b79b28a3bfb8c9c0b057968837126a73603198
Current block number: 9938656
Building bundles
/root/mad-arb/execute/node_modules/@ethersproject/logger/lib/index.js:238
        var error = new Error(message);
                    ^

Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1e+21, code=NUMERIC_FAULT, version=bignumber/5.7.0)
    at Logger.makeError (/root/mad-arb/execute/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/root/mad-arb/execute/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at throwFault (/root/mad-arb/execute/node_modules/@ethersproject/bignumber/lib/bignumber.js:303:19)
    at BigNumber.from (/root/mad-arb/execute/node_modules/@ethersproject/bignumber/lib/bignumber.js:206:17)
    at BundleExecutor.buildBundles (/root/mad-arb/execute/bundleExecutor.js:126:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BundleExecutor.execute (/root/mad-arb/execute/bundleExecutor.js:28:60)
    at async MevShareNode.onmessage (/root/mad-arb/execute/index.js:65:13) {
  reason: 'overflow',
  code: 'NUMERIC_FAULT',
  fault: 'overflow',
  operation: 'BigNumber.from',
  value: 1e+21
}

**Comment by FreedomParrot** [comment]
`

        let bundleOneTransaction = await this.contract.populateTransaction.makeFlashLoan(
            [config.mainnetWETHAddress],
            [ethers.utils.parseUnits("1000", 18)],
            paramsFirstTrade,
            bundleTransactionOptions
        )

        let bundleOne = [
            {hash: _txHash},
            {tx: await this.signer.signTransaction(bundleOneTransaction), canRevert: false},
        ]

        const valuesSecondTrade = [
            _secondPair,
            _firstPair,
            this.percentageToKeep  
        ]

        let paramsSecondTrade = Web3EthAbi.encodeParameters(types, valuesSecondTrade)

        let bundleTwoTransaction = await this.contract.populateTransaction.makeFlashLoan(
            [config.mainnetWETHAddress],
            [ethers.utils.parseUnits("1000", 18)],
            paramsSecondTrade,
            bundleTransactionOptions
        )       

`

**Comment by FreedomParrot** [comment]
Hope it helped this is the right fix for the numeric fault !
